using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;
using Mumei.CodeGen;
using Mumei.CodeGen.Rendering;
using Mumei.CodeGen.Rendering.CSharp;
using Mumei.CodeGen.Roslyn.Components;
using Mumei.CodeGen.Roslyn.RoslynCodeProviders;

namespace Mumei.Roslyn.Testing.CompilationReferenceGenerator;

[Generator]
public sealed class SyntaxTreeReferenceGenerator : IIncrementalGenerator {
    private const string SyntaxTreeReferenceType = "SyntaxTreeReference";

    private const string SyntaxTreeReferenceCode =
        $$"""
          // <auto-generated/>

          // [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
          internal static partial class {{SyntaxTreeReferenceType}} {
            public static global::Mumei.Roslyn.Testing.ICompilationReference Of<T>() {
                throw new global::System.InvalidOperationException("This method is intended to be intercepted at compile time and never invoked directly.");
            }
            
            public static global::Mumei.Roslyn.Testing.ICompilationReference Of(global::System.Type t) {
              throw new global::System.InvalidOperationException("This method is intended to be intercepted at compile time and never invoked directly.");
            }
          }
          """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(static ctx => {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource("SyntaxTreeReference.g.cs", SourceText.From(SyntaxTreeReferenceCode, Encoding.UTF8));
        });

        var p = context.CreateQtProvider(
            (node, ct) => {
                return SyntaxNodeFilter.IsInvocationOf(node, "Of", SyntaxTreeReferenceType);
            },
            static (ctx, ct) => {
                var sourceCodeFactory = ctx.SemanticModel.Compilation.GetTypeByMetadataName(SyntaxTreeReferenceType);
                if (ctx.SemanticModel.GetOperation(ctx.Node) is not IInvocationOperation invocationOp) {
                    return (false, null!, null!);
                }

                if (invocationOp.TargetMethod.TypeArguments.Length != 1 && invocationOp.Arguments.Length != 1) {
                    return (false, null!, null!);
                }

                if (!SymbolEqualityComparer.Default.Equals(invocationOp.TargetMethod.ContainingType, sourceCodeFactory)) {
                    return (false, null!, null!);
                }

                var targetType = invocationOp.TargetMethod.TypeArguments.Length == 1
                    ? invocationOp.TargetMethod.TypeArguments[0]
                    : invocationOp.Arguments[0].Value switch {
                        ITypeOfOperation typeOfOp => typeOfOp.TypeOperand,
                        _ => null
                    };
                return (IsMatch: true, InvocationNode: (InvocationExpressionSyntax) ctx.Node, TargetType: targetType);
            }
        ).Where(x => x.Value.IsMatch);

        var o = p.IncrementalGenerate(static (ctx, expr, ct) => {
            var interceptor = ctx.DeclareClass("SyntaxTreeReferenceInterceptor")
                .WithAccessibility(AccessModifier.Internal + AccessModifier.Partial + AccessModifier.Static);

            var syntaxTreeRef = CreateSyntaxTreeReferenceExpression(
                expr.TargetType!,
                ctx.Compilation
            );

            interceptor.DeclareInterceptorMethod(
                    interceptor.UniqueName("Intercept_Of"),
                    expr.InvocationNode
                )
                .WithBody(ctx.Block(renderTree => {
                    renderTree.Interpolate($"return {syntaxTreeRef};");
                }));

            var toEmit = ctx.Namespace("Generated").WithMember(interceptor);
            ctx.EmitIncremental("SyntaxTreeReferenceInterceptor", toEmit);
        });

        context.RegisterCodeGenerationOutput(o);
    }

    private static ExpressionFragment CreateSyntaxTreeReferenceExpression(
        ITypeSymbol targetType,
        Compilation compilation
    ) {
        if (targetType.DeclaringSyntaxReferences is not [var declarationReference]) {
            throw new InvalidOperationException("Unable to get syntax reference for type.");
        }

        if (declarationReference.GetSyntax() is not TypeDeclarationSyntax typeDeclarationSyntax) {
            throw new InvalidOperationException("Unable to get type declaration syntax.");
        }

        var renderTree = new SourceFileRenderTreeBuilder();

        renderTree.Line("new global::Mumei.Roslyn.Testing.SyntaxTreeCompilationReference {");
        renderTree.StartBlock();

        renderTree.InterpolatedLine($"TypeName = {typeDeclarationSyntax.Identifier.Text:q},");
        renderTree.InterpolatedLine($"SourceCode = \"class root {{}}\",");
        renderTree.Line("References = [");
        renderTree.StartBlock();

        foreach (var memberDeclarationSyntax in typeDeclarationSyntax.Members) {
            if (memberDeclarationSyntax is not TypeDeclarationSyntax typeToEmit) {
                continue;
            }

            var symbol = compilation.GetSemanticModel(typeDeclarationSyntax.SyntaxTree)
                .GetDeclaredSymbol(typeToEmit);

            AppendSyntaxTreeCompilationReference(
                renderTree,
                typeToEmit,
                symbol,
                compilation
            );
        }

        renderTree.EndBlock();
        renderTree.Line("]");
        renderTree.EndBlock();
        renderTree.Text("}");

        return new ExpressionFragment(renderTree.ToString());
    }

    private static void AppendSyntaxTreeCompilationReference(
        IRenderTreeBuilder renderTree,
        TypeDeclarationSyntax typeReference,
        ITypeSymbol typeSymbol,
        Compilation compilation,
        HashSet<ITypeSymbol>? seenTypes = null!
    ) {
        seenTypes ??= new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        if (!seenTypes.Add(typeSymbol)) {
            return;
        }

        renderTree.Line("new global::Mumei.Roslyn.Testing.SyntaxTreeCompilationReference {");
        renderTree.StartBlock();

        var sm = compilation.GetSemanticModel(typeReference.SyntaxTree);
        var typeDeclarationsCoveredByThisType = typeReference.DescendantNodes(x => true)
            .Where(x => x is TypeDeclarationSyntax)
            .Cast<TypeDeclarationSyntax>();

        foreach (var innerTypeDeclarations in typeDeclarationsCoveredByThisType) {
            var symbol = sm.GetDeclaredSymbol(innerTypeDeclarations);
            seenTypes.Add(symbol!);
        }

        var (typeReferences, aliases) = TypeUsageTracker.FindUsedTypes(sm, typeReference);
        var thisTypeDeclarationSource = GetTypeDeclarationSyntaxTree(typeReference, typeSymbol, typeReferences, aliases);

        renderTree.InterpolatedLine($"TypeName = {typeReference.Identifier.Text:q},");
        renderTree.InterpolatedLine($"SourceCode = {thisTypeDeclarationSource},");
        renderTree.Line("References = [");

        renderTree.StartBlock();

        var assemblyReferences = new HashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);
        foreach (var reference in typeReferences) {
            // Declared outside of this compilation
            if (reference.DeclaringSyntaxReferences is []) {
                if (!assemblyReferences.Add(reference.ContainingAssembly)) {
                    continue;
                }

                renderTree.Line("new global::Mumei.Roslyn.Testing.AssemblyCompilationReference {");
                renderTree.StartBlock();
                renderTree.InterpolatedLine($"TypeName = {reference.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat):q},");
                renderTree.InterpolatedLine($"AssemblyName = {reference.ContainingAssembly.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat):q},");
                renderTree.EndBlock();
                renderTree.Line("},");
            }

            if (reference.DeclaringSyntaxReferences is [var declaration]) {
                if (declaration.GetSyntax() is not TypeDeclarationSyntax referencedTypeDeclaration) {
                    continue;
                }

                AppendSyntaxTreeCompilationReference(
                    renderTree,
                    referencedTypeDeclaration,
                    reference,
                    compilation,
                    seenTypes
                );
            }
        }

        renderTree.EndBlock();
        renderTree.Line("]");
        renderTree.EndBlock();
        renderTree.Text("},");
    }

    private static RawStringLiteralFragment GetTypeDeclarationSyntaxTree(
        TypeDeclarationSyntax type,
        ITypeSymbol typeSymbol,
        ImmutableArray<ITypeSymbol> referencedTypes,
        ImmutableArray<IAliasSymbol> aliases
    ) {
        if (type.Modifiers.Any(SyntaxKind.FileKeyword)) {
            type = type.WithModifiers(
                SyntaxFactory.TokenList(type.Modifiers.Where(x => !x.IsKind(SyntaxKind.FileKeyword)))
            );
        }

        if (type.Modifiers.Any(SyntaxKind.PrivateKeyword)) {
            type = type.WithModifiers(
                SyntaxFactory.TokenList(type.Modifiers.Where(x => !x.IsKind(SyntaxKind.PrivateKeyword)))
            );
        }

        var usingDirectives = referencedTypes
            .Distinct(SymbolEqualityComparer.Default)
            .Where(x => x?.ContainingNamespace is not null && !SymbolEqualityComparer.Default.Equals(x.ContainingNamespace, typeSymbol.ContainingNamespace)) // Skip our own namespace
            .Select(t => t!.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Where(x => !typeSymbol.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .StartsWith(x)) // Skip namespaces we're implicitly part of
            .Distinct()
            .Select(x => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(x)))
            .ToList();

        foreach (var alias in aliases.Distinct(SymbolEqualityComparer.Default).OfType<IAliasSymbol>()) {
            usingDirectives.Add(
                SyntaxFactory.UsingDirective(
                    SyntaxFactory.NameEquals(alias.Name),
                    SyntaxFactory.ParseTypeName(alias.Target.Name) // Later we prolly want to spit out all types into their original namespace
                )
            );
        }

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .WithUsings(SyntaxFactory.List(usingDirectives))
            .WithMembers(SyntaxFactory.SingletonList<MemberDeclarationSyntax>(type.WithoutTrivia()))
            .NormalizeWhitespace();

        var sourceCode = compilationUnit.ToFullString();
        return FragmentFactory.RawStringLiteral(sourceCode);
    }
}