using Microsoft.CodeAnalysis;

namespace Mumei.Roslyn.Extensions;

public static class SourceProductionContextExtensions {
  public static void AddGeneratedSource(
    this SourceProductionContext ctx,
    string hintName,
    string content
  ) {
    var fileName = $"{hintName}.g.cs";
    var contentWithAutoGeneratedComment = $"""
                                           // <auto-generated/>

                                           {content}
                                           """;

    ctx.AddSource(fileName, contentWithAutoGeneratedComment);
  }
}