using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Mumei.CodeGen.Qt.TwoStageBuilders.Components;
using Mumei.CodeGen.Qt.TwoStageBuilders.RoslynCodeProviders;

namespace Mumei.CodeGen.Qt;

[Generator]
internal sealed class SyntaxTreeReferenceGenerator : IIncrementalGenerator {
    private const string SyntaxTreeReferenceCode =
        """
        // <auto-generated/>

        internal sealed class _SourceCodeTypeRef;

        [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
        internal static partial class SyntaxTreeReference {
          public static _SourceCodeTypeRef Of<T>() {
              throw new global::System.InvalidOperationException("This method is intended to be intercepted at compile time and never invoked directly.");
          }
          
          public static _SourceCodeTypeRef Of(global::System.Type t) {
            throw new global::System.InvalidOperationException("This method is intended to be intercepted at compile time and never invoked directly.");
          }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(static ctx => {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource("SyntaxTreeReference.g.cs", SourceText.From(SyntaxTreeReferenceCode, Encoding.UTF8));
        });

        var p = context.CreateQtProvider(
            (node, ct) => {
                return SyntaxNodeFilter.IsInvocationOf(node, "Of", "SyntaxTreeReference");
            },
            static (syntaxContext, ct) => {
                return (InvocationExpressionSyntax) syntaxContext.Node;
            }
        ).WithTrackingName("A");

        var o = p.IncrementalCompile(static (compilation, ctx, ct) => {
            var interceptor = compilation.DeclareClass("SyntaxTreeReferenceInterceptor");

            interceptor.DeclareInterceptorMethod(
                interceptor.MakeUniqueName("Intercept_Of"),
                ctx
            ).WithBody(new QtSyntheticRenderCodeBlock((renderTree) => {
                renderTree.Text("return new global::_SourceCodeTypeRef();");
            }));

            var toEmit = compilation.NamespaceFromCompilation("Generated").WithMember(interceptor);
            compilation.TrackForEmission("SyntaxTreeReferenceInterceptor", toEmit);
        }).WithTrackingName("B");

        context.RegisterCompilationOutput(o);
    }
}