using FluentAssertions;
using FluentAssertions.Primitives;
using Microsoft.CodeAnalysis;
using Xunit.Sdk;

namespace Mumei.Roslyn.Testing;

public static class SourceGeneratorTestExtensions {
  public static SourceGeneratorTestAssertions Should(this SourceGeneratorTestResult testResult) {
    return new SourceGeneratorTestAssertions(testResult);
  }
}

public sealed class SourceGeneratorTestAssertions
  : ReferenceTypeAssertions<SourceGeneratorTestResult, SourceGeneratorTestAssertions> {
  protected override string Identifier { get; } = "SourceGeneratorTestResult";

  private readonly SourceGeneratorTestResult _testResult;

  public SourceGeneratorTestAssertions(SourceGeneratorTestResult testResult) : base(testResult) {
    _testResult = testResult;
  }

  public SourceGeneratorGeneratedFileAssertions HaveGeneratedFile(string filePath) {
    var generatedFile = Subject.RunResult.GeneratedTrees.SingleOrDefault(t => t.FilePath.EndsWith(filePath));
    generatedFile.Should().NotBeNull();

    return new SourceGeneratorGeneratedFileAssertions(generatedFile!);
  }
}

public sealed class SourceGeneratorGeneratedFileAssertions
  : ReferenceTypeAssertions<SyntaxTree, SourceGeneratorGeneratedFileAssertions> {
  protected override string Identifier { get; } = "SourceGeneratorGeneratedFiles";

  public SourceGeneratorGeneratedFileAssertions(SyntaxTree tree) :
    base(tree) { }

  public AndConstraint<SourceGeneratorGeneratedFileAssertions> WithContent(string content) {
    var actualContent = Subject.ToString();
    try {
      Assert.Equal(content, actualContent, ignoreLineEndingDifferences: true);
    }
    catch (EqualException e) {
      var exceptionMessage = $"""
                              Expected content:
                              {content}
                              Actual content:
                              {Subject}

                              Difference:
                              {e.Message.Replace("Assert.Equal() Failure\r\n", "")}  
                              """;
      throw new XunitException(exceptionMessage);
    }

    return new AndConstraint<SourceGeneratorGeneratedFileAssertions>(this);
  }

  public AndConstraint<SourceGeneratorGeneratedFileAssertions> WithGeneratedContent(string content) {
    var contentWithAutoGenerated = $"""
                                    // <auto-generated/>

                                    {content}
                                    """;
    return WithContent(contentWithAutoGenerated);
  }
}